[tox]
envlist = py311, lint

[testenv]
deps =
    -r tests/requirements.txt
commands =
    python -m pytest tests/specs

[testenv:lint]
deps =
    black>=24.0.0
    isort>=5.13.0
    flake8>=7.0.0
commands =
    black --check .
    isort --check-only .
    flake8 .
